name: JohnBeveridge
favicon: null
layout_spectrum: 0.27702
typography_spectrum: 0.24381
title: My Take
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a4a8e'
    - '#fea300'
    - '#5ccadc'
    - '#5682b1'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
